### ISSUE TITLE
Using the wrong ICO logo

### ISSUE THREAD

**Issue by edjw** [datarightsfinder/website#30]
We should be using this logo for the ICO on the About page. I have it in .png, .eps, .psd and .svg

![ico-grant-recipient-logo-300x250](https://user-images.githubusercontent.com/6547979/42516834-5f366aa4-8456-11e8-8d9c-0a2036eeeb45.png)

**Comment by ihutc** [comment]
@edjw Hi Ed, could you email me this as .svg and I'll replace it on the about page
