### ISSUE TITLE
Consider respecting DoNotTrack for analytics

### ISSUE THREAD

**Issue by nickcolley** [datarightsfinder/website#33]
Love that you're using a decentralised analytics approach instead of Google Analytics.

Could you consider detecting if the user has DoNotTrack enabled and not tracking the user, or alternatively since you clearly care about people's privacy you could show a message to the user that recognises that you are still tracking them but what you're doing to protect them?

Since this is a hand wavey suggestion, please feel free to close this once you've considered it :)

**Comment by edjw** [comment]
We use Matomo for analytics and it respects Do Not Track (by default I believe)
